- assets/style.css
- index.html
I have added a dark mode toggle button to the website.
> Added Dark mode toggle to the website

- assets/index.js
change download speed value to get the exact download speed
> updated download speed variable in 'js' file

- assets/style.css
Please review my PR and suggest further chnages.
> Change Button Color to red In Dark mode.

- assets/style.css
- index.html
I have added an animation on the button which will work on both modes.
> Add animation to submit button

- .vscode/settings.json
"Issue #29: Remove .vscode file" : fixed
> removed .vscode file

- assets/style.css
- index.html
1.CSS of submit button is changed in both night mode and day mode
> CSS of Submit Button

- indexonchange.html
Also changed the MBps text to Mbps in the calculated result text.
> added another page for auto calculating the values and also linked that page to the main page and vice-versa.

- assets/style.css
Hi,
I have added hover effect to the calculate button and the calulate box was going down of footer so I adjusted it above to improve the UI.
Please accept my PR under Hacktoberfest'21.
> added hover effect to calculate button and improved UI

- assets/index.js
Added alert to check whether input contains any value or not.
Please merge my PR for Hacktoberfest 2021
> Fixed Bugs Added Alert

- README.md
I have improved the UI of readme file. kindly merge it.
> Redesigned README.md

- assets/style.css
- index.html
hover effect for button in dark mode improved and colors for submit button chnag
ed
> hover effect for button in dark mode improved,colors for submit button changed

- index.html
Updated the index.html code so that the submit button reverts back to its original color once dark mode is turned off.
> Submit button color reversion when dark mode is turned off.

- Change the button color in dark mode/index.html
- add css on submit button/index.html
Please review my PR @adithyapaib
> added topic add css on submit button

- assets/style.css
I have changed the color of submit button on hover and also added a faint black shadow effect. Please merge the changes in the project.
> changed the colour and added shadow on hovering on submit button

- index.html
Issue #71 has been resolved.
By using localStorage, the state of the theme is being regained after reloading also.
> Resolved issue #71 in dark mode

- assets/index.js
- index.html
> Fixed the negative value inputs and changed '==' to '==='

- assets/helper.css
- index.html
> Fixed submit button (issue #94)

- index.html
Removed the unused elements from the nav bar. Issue #58
> Removed unused nav elements (issue #58)

- add css on submit button/index.html
> Added some changes to submit button

- index.html
Hope this helps this is occured on the landing page of your website .
The idea of your project is good.
Please merge my pullrequest and appreciate me.
>  I fixed a bug that misaligned (autocalculate) and (Dark/Light mode)on each other

- assets/style.css
- index.html
> align items in navbar

- index.html
> aligning the navbar links issue #82

- assets/helper.css
- assets/index.js
- assets/style.css
- index.html
Trying to resolve the conflicts in thr close PR #64 and #65
> Resolving issues #51 and #52

- assets/helper.css
- assets/style.css
- index.html
I have **changed the color** of submit button in dark mode. Also I have changed the **position of submit button above footer** as it was before. Please review my changes.
> changed the color of button in dark mode

- assets/index.js
Added a feature to calculate days
> Added feature to calculate weeks

- assets/helper.css
- index.html
- indexonchange.html
Issue  #101 : Add footer to Auto Calculate page
> added: footer to Auto Calculate page

- index.html
overlap of the auto calculate link and the icon
> overlap of the auto calculate link and dark mode icon

- Change the button color in dark mode/index.html
- assets/helper.css
- assets/index.js
- assets/style.css
- index.html
- indexonchange.html
This commit resolves and Fixes these issues: #49, #51, #70, #81, #94, #96, #106, #109, #110.
---
* Same code was repeated (probably caused by a merge conflict) that broke the layout of webpage.
* Style sheet code had bugs and missing semicolons (;).
* Submit button's CSS was incorrect, that's why it was below the footer.
*  Footer was above the desired location which caused it to interfere with the Output div.
P.S. There still are a few redundant files and folders which might cause bugs and issues in near future, and need to be deleted. 
---
@adithyapaib kindly accept all incoming changes if any merge conflicts appear, to avoid such broken layout issues in future.
> Layout and Functioning Repaired

- assets/style.css
I have fixed the issues of responsiveness of submit button. Kindly merge it. If there are any conflicts let me know.
> submit button is now responsive

- static/about.css
Enhanced font styles in about.html page 
and Fixed margin in the call below the image
fixed it #242
@adithyapaib
> Updated about.css and font styles in about.html page #242
